# coding=utf-8
import os

import datetime
import pdfkit

cv_name = 'KALIPRASAD_RAY_2017'
html_file = "../gen/" + cv_name + '.html'
pdf_file = "../gen/" + cv_name + '.pdf'
cover = "../gen/" + 'cover.html'

if not os.path.exists("../gen"):
    os.mkdir("../gen")

def footer(mail, name, gen_time):
    return \
        '''
        <footer>
            <p align="middle">The html/pdf is generated by python project hosted on \
             <a href="https://github.com/Kalinga/pythonLearning/tree/master/project">GitHub</a> at {2}
            </p>
            <p align="middle">Contact \
             <a href={0}>{1}</a> \
             with your questions, comments, and suggestions
            </p>
        </footer>
        '''.format(mail, name, gen_time)

def emptylines(no):
    return '''<br>''' * no

def htmlstart(title_name):
    return \
        '''
        <!DOCTYPE html>
        <html>

            <head>
                <title>{0}</title>
                <meta charset="UTF-8">
                <link href="../src/main.css" rel="stylesheet" type="text/css">
            </head>
        '''.format(title_name)

def pageheading():
    return \
        '''
        <body>
            <div id="Container">
                <article class="Container_article">
                    <h3>Kaliprasad Ray</h3>
                    <address>
                        +91-9124587714<br>
                        Bayalishibati<br>
                        Gop, Puri<br>
                        Odisha<br>
                        PIN: 752110<br>
                        <a href="mailto:raykaliprasad@gmail.com">raykaliprasad@gmail.com</a><br>
                    </address>
                </article>
                <article class="Container_article" id="rightMostImage">
                    <img src="../img/kalia_photo.png" alt="Kaliprasad's photo">
                </article>
            </div >
        '''

def intro():
    return \
        '''
        <h4>ITI Mechanic</h4>
        <p>Solid four months advance theoretical knowledge with practical experience has made me a better
            professional mechanic after passing my ITI in Electrical trade. Currently I am looking for
            a job in a growing company where i can apply my skills and knowledge.
        </p>
        '''

def technical():
    return \
        '''
        <h4>Technical Domain:</h4>
                <p>Inspection and maintenance of electrical machines</p>
                <ul>
                    <li>Electric hardware and control</li>
                    <li>Mould</li>
                    <li>AutoCAD</li>
                    <li>eCAD</li>
                    <li>Programmable  logic control</li>
                    <li>Pneumatic</li>
                    <li>Hydraulic</li>
                    <li>Machine Lab</li>
                    <li>Electronics</li>
                </ul>
                <hr>
        '''

def functional():
    return \
        '''
        <h4>Functional Domain:</h4>
                <ul>
                    <li>Car Multimedia Application development</li>
                    <li>Service framework development</li>
                    <li>Interface Test Automation</li>
                    <li>Media Player and Media Gallery</li>
                    <li>Webkit based web browser</li>
                    <li>Predictive Input method solution</li>
                </ul>
                <hr>
        '''
def keyresponsibilities():
    return \
        '''
        <h4>Key Responsibilities:</h4>
        <ul>
            <li>Assemble, install, test, and maintain electrical or electronic wiring, equipment, appliances</li>
            <li>Diagnose malfunctioning systems and components</li>
            <li>Inspect electrical systems, equipment, and components to identify defects, and the need for
                adjustment or repair</li>
            <li>Install ground leads and connect power cables to equipment, such as motors</li>
            <li>Repair or replace wiring, equipment using hand tools and power tools</li>
        </ul>
        <hr>
        '''

def experience(position, company, duration):
    return \
        '''
        <h5>''' + position + '''</h5>
        <div>
            <article><h6>''' + company + '''</h6>
            </article>
            <article style="float:right"> <h6>''' + duration + '''</h6>
            </article>
        </div>
        <!--hr-->
        '''

def experiences():
    return \
    '''<h4>EXPERIENCE:</h4>''' + \
    experience("Machine/Electrician Trainee",
               "Central Tool Room & Training Centre,Bhubaneswar",
               "Oct'16-Present")


def education(institution, certificate, duration, percentage):
    return \
        '''
        <div>
            <article><h6>''' + institution + " | " + certificate + ''' with ''' + percentage + '''%''' + '''</h6>
            </article>
            <article style="float:right;"> <h6>''' + duration + '''</h6>
            </article>
        </div>
        <!--hr-->
        '''

def educations():
    return \
        '''
        <br><h4>EDUCATION:</h4>''' + \
        education("CTTC,Bhubaneswar",
                  "Certificate Course in advance machine maintenance",
                  "Oct' 2016- Till Date", "80") + \
        education("Sailabala Memorial ITC, Nimapara",
                  "ITI Electrical",
                  "July' 2014- July' 2016", "70") + \
        education("Board of secondary Education, Orissa",
                  "High school Certificate Examination ",
                  "Jun 2013- Jul 2014", "51")


def personal():
    return \
        '''
        <h5>PERSONAL DETAILS</h5>
        <table>
          <tr>
            <td>Date of Birth</td>
            <td>15 Nov 1991</td>
          </tr>
          <tr>
            <td>Marital Status</td>
            <td>Married</td>
          </tr>
        </table>
        '''

def htmlend():
    return \
        '''
            </body>
        </html>
        '''
contact_email = "mailto:raykaliprasad@gmail.com"
contact_name = "Kaliprasad Ray"

def mycover(manager_name, company_name):
     hiring_manager = manager_name if manager_name else "Hiring Manager"
     org_name = company_name if company_name else "Organisation"
     str = u'''
        <body>
            <p> Dear {0},<br><br>
            &nbsp;&nbsp;&nbsp;&nbsp;I found you are in search for a dynamic and highly motivated Software Engineer for
            your company. The job description is so exciting and very much closely matching my experience and ambitions.
            With around 10 years of experience in IT, i am confident that i can step in and make immediate contribution
            to the project and valuable contribution to {1}'s continued success.<p>

            <p>&nbsp;&nbsp;&nbsp;&nbsp;As a software engineer at {1}, I can collaborate closely with Customers,
            and help junior team members with my knowledge and experience. In addition, I consider myself a flexible,
            always wanted to take responsibility, take ownership of core components. I consider myself a quick learner
            and have motivation towards learning new technologies and apply them in solving real world problems.<p>

            <p>&nbsp;&nbsp;&nbsp;&nbsp;I look forward to discuss further on details of this position. In the meantime,
            please take a look at my resume attached. Please feel free to contact for additional information
            required if any.
            <p><br>

            <p>Mit freundlichen Grüßen / Best regards,<br>
            Kalinga Bhusan Ray<br>
            +917795346374<br>
            </p>

        '''.format(hiring_manager, org_name).encode("utf-8")
     return  str

def skeleton():
    return \
        htmlstart(contact_name) \
        + pageheading() \
        + intro() \
        + technical() \
        + keyresponsibilities() \
        + experiences() \
        + educations() \
        + htmlend()

with open(html_file,'w+') as f:
    message = skeleton()

    f.write(message)

manager_name = ''
company_name = ""
def cover_page():
    return \
        htmlstart(contact_name) + \
        mycover(manager_name, company_name) + \
        htmlend()


with open(cover,'w+') as f:
    message = cover_page()
    f.write(message)

pdfkit.from_file(html_file, pdf_file)
