# coding=utf-8
import os

import datetime
import pdfkit

cv_name = 'SONALI_DAS_2017'
html_file = "../gen/" + cv_name + '.html'
pdf_file = "../gen/" + cv_name + '.pdf'
cover = "../gen/" + 'cover.html'

if not os.path.exists("../gen"):
    os.mkdir("../gen")

def footer(mail, name, gen_time):
    return \
        '''
        <footer>
            <p align="middle">The html/pdf is generated by python project hosted on \
             <a href="https://github.com/Kalinga/pythonLearning/tree/master/project">GitHub</a> at {2}
            </p>
            <p align="middle">Contact \
             <a href={0}>{1}</a> \
             with your questions, comments, and suggestions
            </p>
        </footer>
        '''.format(mail, name, gen_time)

def emptylines(no):
    return '''<br>''' * no

def htmlstart(title_name):
    return \
        '''
        <!DOCTYPE html>
        <html>

            <head>
                <title>{0}</title>
                <meta charset="UTF-8">
                <link href="../src/main.css" rel="stylesheet" type="text/css">
            </head>
        '''.format(title_name)

def pageheading():
    return \
        '''
        <body>
            <div id="Container">
                <article class="Container_article">
                    <h3>Sonali Das</h3>
                    <address>
                        +91-8951606750<br>
                        Narendra Kona, Jatiababa Jaga<br>
                        Puri,Odisha <br>
                        PIN: 752001<br>
                        <a href="mailto:kaushiky.das@gmail.com">kaushiky.das@gmail.com</a><br>
                    </address>
                </article>
                <article class="Container_article" id="rightMostImage">
                    <img src="../img/sonali_photo.png" alt="Sonali's photo">
                </article>
            </div >
        '''

def intro():
    return \
        '''
        <h4>Experienced Professional</h4>
        <p>I have experience in academic sector as well as in corporate functions (purchasing department of a leading
        tile and ceramic company in Bangalore). With good negotiation skill and pursuing power, I can co-ordinate Parents
        teacher meeting and vendors meeting and other required business events.
        </p>
        '''

def technical():
    return \
        '''
        <h4>Key IT  Skills:</h4>
                <ul>
                    <li>Microsoft Word</li>
                    <li>Excel</li>
                    <li>DTP</li>
                    <li>ERP</li>
                </ul>
                <hr>
        '''

def functional():
    return \
        '''
        <h4>Other Skill:</h4>
                <ul>
                    <li>Event Organisation</li>
                    <li>Consultation</li>
                    <li>Understanding students and solving their problem</li>
                </ul>
                <hr>
        '''
def keyresponsibilities():
    return \
        '''
        <h4>Key Responsibilities:</h4>
        <ul>
            <li>Teaching</li>
            <li>Interacting Parents</li>
            <li>Consulting incoming Parents</li>
            <li>Price negotiation with exisitng vendors</li>
            <li>Searching and expanding vendor base</li>
        </ul>
        <hr>
        '''

def experience(position, company, duration):
    return \
        '''
        <h5>''' + position + '''</h5>
        <div>
            <article><h6>''' + company + '''</h6>
            </article>
            <article style="float:right"> <h6>''' + duration + '''</h6>
            </article>
        </div>
        <!--hr-->
        '''

def experiences():
    return \
    '''<h4>EXPERIENCE:</h4>''' + \
    experience("Teacher",
               "I Play I Learn, Hyderabad",
               "Six Months") + \
    experience("Assistant purchase manager",
               "StonArts.D, Bangalore",
               "12 Months")

def certificate(cert, institute, duration):
    return \
        '''
        <h5>''' + cert + '''</h5>
        <div>
            <article><h6>''' + institute + '''</h6>
            </article>
            <article style="float:right"> <h6>''' + duration + '''</h6>
            </article>
        </div>
        <!--hr-->
        '''

def certificates():
    return \
    '''<h4>CERTIFICATION:</h4>''' + \
    certificate("German Language A1",
                "Deutschland",
                "2015") + \
    certificate("Nursery teacher Traing",
              "I Play I Learn, Hyderbad",
              "2011") + \
    certificate("DTP",
               "XXX",
               "2007") + \
    certificate("Skill development",
               "OCAC, Puri", "2006")

def education(institution, certificate, duration, percentage):
    return \
        '''
        <div>
            <article><h6>''' + institution + " | " + certificate + ''' with ''' + percentage + '''%''' + '''</h6>
            </article>
            <article style="float:right;"> <h6>''' + duration + '''</h6>
            </article>
        </div>
        <!--hr-->
        '''

def educations():
    return \
        '''
        <br><h4>EDUCATION:</h4>''' + \
        education("S.C.S. (A) COLLEGE, Puri",
                  "MA, ORIYA(H)",
                  "2010", "73") + \
        education("S.C.S. (A) COLLEGE, Puri",
                  "+3 ARTS",
                  "2008", "63") + \
        education("Womens College, Puri",
                  "+2 ARTS",
                  "2005", "47") + \
        education("Board of secondary Education, Orissa",
                  "High school Certificate Examination ",
                  "2003", "48")


def personal():
    return \
        '''
        <h5>PERSONAL DETAILS</h5>
        <table>
          <tr>
            <td>Date of Birth</td>
            <td>07 Jun 1988</td>
          </tr>
          <tr>
            <td>Marital Status</td>
            <td>Married</td>
          </tr>
          <tr>
            <td>Languages</td>
            <td>Oriya, Hindi, English, German</td>
          </tr>
        </table>
        '''

def personalDelaration():
    return \
        '''
        <h6>DECLARATION</h6>
        <p>I do hereby declare that the above information is true to the best of my knowledge.</p>
        '''

def htmlend():
    return \
        '''
            </body>
        </html>
        '''
contact_email = "mailto:kaushiky.das@gmail.com"
contact_name = "Sonali Das"

def mycover(manager_name, company_name):
     hiring_manager = manager_name if manager_name else "Hiring Manager"
     org_name = company_name if company_name else "Organisation"
     str = u'''
        <body>
            <p> Dear {0},<br><br>
            &nbsp;&nbsp;&nbsp;&nbsp;I found you are in search for a dynamic and highly motivated Software Engineer for
            your company. The job description is so exciting and very much closely matching my experience and ambitions.
            With around 10 years of experience in IT, i am confident that i can step in and make immediate contribution
            to the project and valuable contribution to {1}'s continued success.<p>

            <p>&nbsp;&nbsp;&nbsp;&nbsp;As a software engineer at {1}, I can collaborate closely with Customers,
            and help junior team members with my knowledge and experience. In addition, I consider myself a flexible,
            always wanted to take responsibility, take ownership of core components. I consider myself a quick learner
            and have motivation towards learning new technologies and apply them in solving real world problems.<p>

            <p>&nbsp;&nbsp;&nbsp;&nbsp;I look forward to discuss further on details of this position. In the meantime,
            please take a look at my resume attached. Please feel free to contact for additional information
            required if any.
            <p><br>

            <p>Mit freundlichen Grüßen / Best regards,<br>
            Kalinga Bhusan Ray<br>
            +917795346374<br>
            </p>

        '''.format(hiring_manager, org_name).encode("utf-8")
     return  str

def skeleton():
    return \
        htmlstart(contact_name) \
        + pageheading() \
        + intro() \
        + technical() \
        + keyresponsibilities() \
        + experiences() \
        + educations() \
        + certificates() \
        + personal() \
        + personalDelaration() \
        + htmlend()

with open(html_file,'w+') as f:
    message = skeleton()

    f.write(message)

manager_name = ''
company_name = ""
def cover_page():
    return \
        htmlstart(contact_name) + \
        mycover(manager_name, company_name) + \
        htmlend()


with open(cover,'w+') as f:
    message = cover_page()
    f.write(message)

pdfkit.from_file(html_file, pdf_file)
