import os
import pdfkit

kalinga = 'KALINGA_RAY_2017'
html_file = "../gen/" + kalinga + '.html'
pdf_file = "../gen/" + kalinga + '.pdf'

if not os.path.exists("../gen"):
    os.mkdir("../gen")

def footer():
    return \
        '''
        <footer>
            <p align="middle">The html/pdf is generated by python project hosted at \
             <a href="https://github.com/Kalinga/pythonLearning/tree/master/project">GitHub</a>
            </p>
            <p align="middle">Contact \
             <a href="mailto:mail.kalinga@gmail.com">Kalinga Bhusan Ray</a> \
             with your questions, comments, and suggestions
            </p>
        </footer>
        '''

def emptylines(no):
    return '''<br>''' * no

def htmlstart():
    return \
        '''
        <!DOCTYPE html>
        <html>

            <head>
                <title>Kalinga Bhusan Ray</title>
                <meta charset="UTF-8">
                <link href="../src/main.css" rel="stylesheet" type="text/css">
            </head>
        '''

def pageheading():
    return \
        '''
        <body>
            <div id="Container">
                <article>
                    <h1>Kalinga Bhusan Ray</h1>
                    <address>
                        +91-7795346374<br>
                        Adugodi<br>
                        Bangalore<br>
                        India<br>
                        PIN: 560030<br>
                        <a href="mailto:mail.kalinga@gmail.com">mail.kalinga@gmail.com</a><br>
                    </address>
                </article>
                <article id="rightMostImage">
                    <img src="../src/myimage1.jpg" alt="Kalinga's photo">
                </article>
            </div >
        '''

def intro():
    return \
        '''
        <h2>SPECIALIST</h2>
        <p>Software engineer with 10 years experience in IT industry, in various domains,
            specializing in Car Multimedia application and Mobile application development.
            1.5yrs of working and living experience in Germany, Hildesheim. Have motivation towards learning
            German language and completed A2 (Deutsche Sprache) course
        </p>
        '''

def technical():
    return \
        '''
        <h3>Technical Domain:</h3>
                <p>Application and Framework development using C, C++, Symbian C++, Core Java, Xtend/Xtext, DSL, Python
                </p>
                <ul>
                    <li>Application development for Linux, Symbian, MeeGo devices</li>
                    <li>Working knowledge of Android</li>
                    <li>GUI development using QT, QML, gtk, UIQ, S60</li>
                    <li>Working knowledge of HTML , XML Java Script, Shell script, Perl</li>
                    <li>Git, ClearCase, Subversion,Eclipse, Carbide, CodeWarior, UML and many other tools</li>
                    <li>TDD, Unit testing (JUnit, Google Test), Integration Testing</li>
                    <li>Agile methodologies, Scrum, Planning & Estimation, CI(Jenkins)</li>
                </ul>
                <hr>
        '''

def functional():
    return \
        '''
        <h3>Functional Domain:</h3>
                <ul>
                    <li>Car Multimedia Application development</li>
                    <li>Media Player and Media Gallery</li>
                    <li>Webkit based web browser</li>
                    <li>Predictive Input method solution</li>
                    <li>Service framework development</li>
                    <li>Interface Test Automation</li>
                </ul>
                <hr>
        '''


def experience(position, company, duration):
    return \
        '''
        <h4>''' + position + '''</h4>
        <div>
            <article><h5>''' + company + '''</h5>
            </article>
            <article style="float:right"> <h5>''' + duration + '''</h5>
            </article>
        </div>
        <hr>
        '''

def experiences():
    return \
    '''<h3>EXPERIENCE:</h3>''' + \
    experience("Specialist- Car Multimedia",
               "Robert Bosch Engineering and Business Solutions, Bangalore",
               "Dec'11-Present") + \
    experience("Senior Software Engineer-R&D (Adaptxt)",
               "Keypoint technology, Hyd",
               "Mar'10-Dec'11") + \
    experience("Senior Software Engineer (Azingo Browser)",
               "Azingo Soft Systems India PVT LTD, Hyd",
               "May'09-Mar'10") + \
    experience("Software Engineer- (Sasken Media Player)",
               "Sasken Communication Technologies, Bangalore",
               "Dec'06-May'09") + \
    experience("MIS executive",
               "iSeva,E4E Pvt ltd, Bangalore",
               "Apr'06-Dec'06")

def education(institution, certificate, duration, percentage):
    return \
        '''
        <div style="display: inline-block">
            <div align="justify">
                <article><p>''' + institution + " | " + certificate + ''' with ''' + percentage + '''%''' + '''</p>
                </article>
            </div>
            <div width="50%">
            <article style="float:right"> <h5>''' + duration + '''</h5>
            </article>
            </div>
        </div>
        <hr>
        '''

def educations():
    return \
        '''
        <br><h3>EDUCATIONS:</h3>''' + \
        education("ABIT Cuttack, Odisha",
                  "BE Computer Science and Engineering",
                  "2001-2005", "71") + \
        education("Council of Higher Secondary Education, Orissa",
                  "Higher Secondary Examination Certificate",
                  "1998-2000", "65") + \
        education("Board of secondary Education, Orissa",
                  "High school Certificate Examination ",
                  "1997-1998", "78")

def personal():
    return \
    '''
    <h6>PERSONAL DETAILS</h6>
    <table>
      <tr>
        <td>Date of Birth</td>
        <td>02 June 1983</td>
      </tr>
      <tr>
        <td>Marital Status</td>
        <td>Married</td>
      </tr>
      <tr>
        <td>Languages Known</td>
        <td>English, Hindi and Oriya, German(A2)</td>
      </tr>
      <tr>
        <td>Passport Number</td>
        <td>G6513632</td>
      </tr>
    </table>
    '''

def htmlend():
    return \
        '''
            </body>
        </html>
        '''

def skeleton():
    return \
        htmlstart() \
        + pageheading() \
        + intro() \
        + technical() \
        + functional() \
        + emptylines(4) \
        + footer() \
        + experiences() \
        + educations() \
        + personal() \
        + footer() \
        + htmlend()

with open(html_file,'w+') as f:
    message = skeleton()

    f.write(message)



pdfkit.from_file(html_file, pdf_file)
